export const SERVICE_OPTIONS = [
  'Desarrollo Web',
  'Gestión de Redes Sociales',
  'Campañas Publicitarias',
  'SEO y Posicionamiento',
  'GEO',
  'Formación Digital',
  'Automatizaciones',
  'Diseño y Branding',
  'CRM y ERP',
  'Desarrollo de Apps a medida',
  'Estrategia Digital',
  'Producción de Vídeos y Spots con IA',
  'No estoy seguro / Necesito orientación',
];
